slogan: "Hacking means exploring the limits of what is possible, in a spirit of playful cleverness."

theme: bootstrap
inverse: true

menu:
  - title: 归档
    url: archives
    intro: "所有的文章。"
    icon: "fa fa-archive"
  - title: 分类
    url: categories
    intro: "所有的分类。"
    icon: "fa fa-folder"
  - title: 标签
    url: tags
    intro: "所有的标签。"
    icon: "fa fa-tags"
  - title: 关于
    url: about
    intro: "关于。"
    icon: "fa fa-user"

links:
  - title: "myyerrol的GitHub"
    url: http://www.github.com/myyerrol
    intro: "我的GitHub。"
    icon: "fa fa-github"
  - title: "maksyuki的GitHub"
    url: http://www.github.com/maksyuki
    intro: "maksyuki的GitHub。"
    icon: "fa fa-github"
  - title: "mawenke的GitHub"
    url: http://www.github.com/mawenke
    intro: "mawenke的GitHub。"
    icon: "fa fa-github"
  - title: "liao-zhihan的GitHub"
    url: http://www.github.com/liao-zhihan
    intro: "liao-zhihan的GitHub。"
    icon: "fa fa-github"
  - title: "西工大RoboCup@Home的GitHub"
    url: http://www.github.com/xm-project
    intro: "西工大RoboCup@Home的GitHub。"
    icon: "fa fa-github"
  - title: "西工大RoboCup@Rescue的GitHub"
    url: http://www.github.com/team-explorer-rescue-robot
    intro: "西工大RoboCup@Rescue的GitHub。"
    icon: "fa fa-github"
  - title: "西工大篮球机器人项目的GitHub"
    url: http://www.github.com/nwpu-basketball-robot
    intro: "西工大篮球机器人项目的GitHub。"
    icon: "fa fa-github"
  - title: "HeadsFree项目的GitHub"
    url: http://www.github.com/HANDS-FREE
    intro: "HeadsFree项目的GitHub。"
    icon: "fa fa-github"
  - title: "maksyuki的博客"
    url: http://www.maksyuki.com
    intro: "maksyuki的博客。"
    icon: "fa fa-globe"
  - title: "mawenke的博客"
    url: https://mawenke.github.io
    intro: "mawenke的博客。"
    icon: "fa fa-globe"
  - title: "HandsFree项目的网站"
    url: http://www.hands-free.org.cn
    intro: "HandsFree项目的网站。"
    icon: "fa fa-globe"
  - title: "HandsFree项目的维基"
    url: https://github.com/HANDS-FREE/HANDS-FREE.github.io/wiki
    intro: "HandsFree项目的维基。"
    icon: "fa fa-globe"
  - title: "myyerrol的邮箱"
    url: mailto:myyerrol@126.com
    intro: myyerrol的邮箱。
    icon: "fa fa-envelope"

widgets:
- search
- category
- tagcloud
- recent_posts
- links

rss:
fancybox: true
favicon: images/favicon/favicon.ico
duoshuo_shortname:

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR

# share widgets
bdshare: false
jiathis: false
